id: P8A802645
initial_creation_type: input
source_metadata:
  Title: Mahāparinirvāṇa Sūtra
  Editor: Ernst Waldsmidt
  Publisher: Academie Verlag
  Place of Publication: Berlin
  Year: '1950'
  Mahāparinirvāṇa sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:05:08.794013'
last_modified_at: '2022-03-08T16:05:08.794025'
